### ISSUE TITLE
Discuss approach to helping ASPA and associated agencies develop a strategy for adopting USWDS.

### ISSUE THREAD

**Issue by nks-bix** [uswds/uswds-team#5] opened 2020-04-30 15:20 UTC
Discuss approach to helping ASPA and associated agencies develop a strategy for adopting USWDS.

**Comment by afeijoo** [comment] 2020-04-30 17:11
This is a duplicate of https://github.com/uswds/uswds-team/issues/6, so I'm closing it.

**Closed by afeijoo** 2020-04-30 17:11 UTC
